name: Create GitHub Release Draft

on: workflow_call

jobs:
  release-draft-with-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update CHANGELOG
        uses: dlavrenuek/conventional-changelog-action@v1.2.1
#2        uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: "1.25.0"
          to: "1.25.1"

#      - name: Update CHANGELOG
#        id: changelog
#        uses: Requarks/changelog-action@v1
#        with:
#          token: ${{ github.token }}
#          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ github.ref_name }}
#          body: ${{ steps.changelog.outputs.changes }}
#2          body: ${{ steps.changelog.outputs.changelog }}
          body: ${{ steps.changelog.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
