name: Maven Verify

on: workflow_call

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'ci(release):')"

    steps:
      - uses: actions/checkout@v3

      - name: Get Java-Version from pom.xml
        id: get-java-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '//*[local-name()="maven.compiler.release"]'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.get-java-version.outputs.info }}
          distribution: 'adopt'
          cache: 'maven'
          
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


