name: Maven Release

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      GPG_KEY_ID:
        required: true
      GPG_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Java-Version from pom.xml
        id: get-java-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '//*[local-name()="maven.compiler.release"]'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.get-java-version.outputs.info }}
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Extract version from pom.xml
        id: extract_gav
        uses: andreacomo/maven-gav-extractor@v1

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.extract_gav.outputs.version }}

      #
      # Release (main branch)
      #
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        if: github.ref == 'refs/heads/main'
        env:
          JAVA_HOME: /usr/lib/jvm/java-${{ steps.get-java-version.outputs.info }}-openjdk/
        with:
          git-release-bot-name: "sitepark-bot"
          git-release-bot-email: "github@sitepark.com"
          release-branch-name: "main"
          version-minor: true

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}


      #
      # Hotfix (hotfix/[0-9]i+.[0-9]+.x branch)
      #
      - name: Hotfix
        uses: qcastel/github-actions-maven-release@master
        if: "startsWith(github.ref, 'refs/heads/hotfix/')"
        env:
          JAVA_HOME: /usr/lib/jvm/java-${{ steps.get-java-version.outputs.info }}-openjdk/
          SKIP_GIT_SANITY_CHECK: true
        with:
          git-release-bot-name: "sitepark-bot"
          git-release-bot-email: "github@sitepark.com"
          release-branch-name: "${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.x"
          version-patch: true

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}

      #
      # Support-Fix (support/[0-9]+.x branch)
      #
      - name: Support-Fix
        uses: qcastel/github-actions-maven-release@master
        if: "startsWith(github.ref, 'refs/heads/support/')"
        env:
          JAVA_HOME: /usr/lib/jvm/java-${{ steps.get-java-version.outputs.info }}-openjdk/
          SKIP_GIT_SANITY_CHECK: true
        with:
          git-release-bot-name: "sitepark-bot"
          git-release-bot-email: "github@sitepark.com"
          release-branch-name: "${{ steps.semver_parser.outputs.major }}.x"
          version-patch: true

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
