name: Maven Verify

on: workflow_call

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'ci(release):')"

    steps:
      - uses: actions/checkout@v3

      - name: set java version
        id: java-version
        run: |
          version=11
          echo "::set-output name=version::$version"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.java-version.outputs.version }}
          distribution: 'adopt'
          cache: 'maven'
          
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


