name: Publish Maven Release

on: workflow_call

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Maven Artifact
        run:
           echo "publish maven artifact $GITHUB_REF"
