on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string


jobs:
  start-hotfix:

    if: "startsWith(inputs.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - id: get-version
        run: |
          version=$(echo ${{inputs.ref}} | cut -d/ -f3)
          echo "::set-output name=version::$version"

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.get-version.outputs.version }}

      - name: Start Hotfix
        run:
           echo "start hotfix ${{ steps.get-version.outputs.version }}"

      - name: Checkout release
        uses: actions/checkout@v3
        with:
           ref: ${{inputs.ref}}


      - name: Create hotifx branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           branch: "hotfix/${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.x"

      - name: Checkout hotifx branch
        uses: actions/checkout@v3
        with:
           ref: hotfix/${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.x

      - name: Extract version from pom.xml
        id: extract_gav
        uses: andreacomo/maven-gav-extractor@v1

      - name: Check if hotfix already started
        if: "endsWith(steps.extract_gav.outputs.version, '-SNAPSHOT')"
        run:
           echo "hotfix already started"
           exit 1

      - name: Setup java
        uses: actions/setup-java@v3
        if: success()
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Set next hotfix version
        if: success()
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.1-SNAPSHOT

      - name: Commit pom.xml
        uses: EndBug/add-and-commit@v9
        if: success()
        with:
           message: "ci(release): set next hotfix version"




