on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string


jobs:
  start-hotfix:

    if: "startsWith(inputs.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - id: get-version
        run: |
          version=$(echo ${{inputs.ref}} | cut -d/ -f3)
          echo "::set-output name=version::$version"

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.get-version.outputs.version }}

      - name: Start Hotfix
        run:
           echo "start hotfix ${{ steps.get-version.outputs.version }}"

      - uses: actions/checkout@v3
        with:
           ref: ${{inputs.ref}}


      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           branch: "hotfix/${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.x"

      - uses: actions/checkout@v3
        with:
           ref: hotfix/${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.x

      - name: Extract GAV
        id: extract_gav
        uses: andreacomo/maven-gav-extractor@v1

      - name: Set Version
        run:
           echo "current version ${{ steps.extract_gav.outputs.version }}"
